FROM node:22-alpine AS development

RUN apk update && apk upgrade --no-cache

WORKDIR /app

RUN apk add --no-cache python3 make g++ openssl

COPY package.json ./
COPY yarn.lock* ./

RUN yarn install

COPY . .

RUN npx prisma generate --schema prisma/schema.prisma

EXPOSE 3000

CMD ["yarn", "dev"]
